### ISSUE TITLE
How to trigger Extended Link Copy in Firefox?

### ISSUE THREAD

**Issue by peter-lyons-kehl** [agorodezki/extended-link-copy#1]
Dear Tobias,

Thank you for Extended Link Copy. Your add-on will save people time. How productive.

You documented and referenced the regex well - both on GitHub and at about:addons > Extended Link Copy > Preferences. However, the start point is missing: How do users invoke the copy (and how do they select an option)?

In add-on Preferences, it lists the default descriptions:
Copy just the domain
Copy url without attributes
Copy just the attributes
...

But I can't see a way to use them. I tried with various websites. I tried right-click on the page, at various parts of Firefox toolbar, right clicked at Firefox toolbar > Customize.... .. I run Firefox 60.0.1 on openSUSE Linux (GNOME).

When I installed in Chrome (Chromium on Linux), I see 'E' icon in the toolbar. Again, I can configure it, but not trigger it.

Would you document exact sequence steps. Describe where to click (right click/left click), what keys to press. Screenshots ideally, please.

Thank you in advance.

**Comment by peter-lyons-kehl** [comment]
Hi Tobias,

You've documented it, of course: under Firefox special address about:addons > Extended Link Copy > More or Preferences > "in the context menu of every hyperlink." However, that instruction is a starting point for new users. Even worse, it's "hidden" in the long text.

May I suggest you re-order it in the documentation, to the beginning. Even better, add a screenshot of the context menu, please.

**Comment by agorodezki** [comment]
Hi Peter,

thanks for your hint. I added a small usage section to the readme.

**Comment by peter-lyons-kehl** [comment]
Hi Tobias,

Are you on LinkedIn? Is this your board: https://www.linkedin.com/in/tobias-bernrieder-009535a4?

Let's connect.
https://www.linkedin.com/in/peterkehl
