### ISSUE TITLE
Promote Extended Link Copy

### ISSUE THREAD

**Issue by peter-lyons-kehl** [agorodezki/extended-link-copy#2]
Hi Tobias,

You could make it easier for users to locate the download. Would you add:

Firefox download: https://addons.mozilla.org/en-US/firefox/addon/extended-link-copy
Chrome download: https://chrome.google.com/webstore/detail/extended-link-copy/bjjgidcnpbnkkhgkalagihljbjdpolim

to README.md, please.

Update Chrome link everytime you deploy a new version.

**Comment by agorodezki** [comment]
Hi Peter,

thanks for your hint. Download links are added
